# Malaria Detection Training Configuration
# EfficientNet-B0 with clinical focus on high sensitivity

model:
  name: "efficientnet-b0"
  num_classes: 1
  pretrained: true
  dropout: 0.2
  use_timm: false

data:
  data_dir: "data"
  image_size: 224
  num_workers: 4

training:
  batch_size: 32
  epochs: 50
  learning_rate: 3e-4
  weight_decay: 1e-5
  optimizer: "adamw"  # adamw, sgd
  
  # Loss function: bce, focal, clinical
  loss_function: "clinical"
  
  # Focal loss parameters (if using focal)
  focal_alpha: 1.0
  focal_gamma: 2.0
  
  # Clinical loss parameters (if using clinical)
  sensitivity_weight: 2.0  # Higher weight for detecting parasites
  specificity_weight: 1.0
  
  # Scheduler
  scheduler: "cosine"  # cosine, plateau
  scheduler_patience: 3
  
  # Early stopping
  early_stopping: true
  early_stopping_patience: 7
  
  # Checkpoints
  checkpoint_dir: "checkpoints"

logging:
  log_dir: "logs"
  tensorboard_dir: "runs"
  log_interval: 50
  
  # Wandb (optional)
  use_wandb: false
  wandb_project: "malaria-detection"

# Clinical validation thresholds
clinical:
  target_sensitivity: 0.95  # Minimum sensitivity for clinical use
  target_specificity: 0.85  # Minimum specificity
  confidence_threshold: 0.5  # Default classification threshold
